server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: demo
  resource: springboot-keycloak
  public-client: true
  bearer-only: true


spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/keycloak
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true



